const Bestsellproducts =[
      {
        id:1,
        img:"images/product-3.png",
        offer:"20% off",
        title:"Cottage Red",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },

      {
        id:2,
        img:"images/product-5.png",
        offer:"",
        title:"Dry Riesling",
        cate:"organic",
        oldprice:"28.00",
        price:"25.00",
        link:"/shop",
      },
      {
        id:3,
        img:"images/product-7.png",
        offer:"20% off",
        title:" 2003 Smith Woodhouse – 750ml ",
        cate:"indian wine",
        oldprice:"40.00",
        price:"30.00",
        link:"/shop",
      },

      {
        id:4,
        img:"images/product-8.png",
        offer:"",
        title:" 2017 Cabernet Sauvignon ",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },
      {
        id:5,
        img:"images/product-9.png",
        offer:"50% off",
        title:"  Pinot Grigio ",
        cate:"organic",
        oldprice:"30.00",
        price:"15.00",
        link:"/shop",
      },

      {
        id:6,
        img:"images/product-3.png",
        offer:"40% off",
        title:"Nebbiolo d'Alba Rizieri",
        cate:"mead",
        oldprice:"20.00",
        price:"25.00",
        link:"/shop",
      },
      {
        id:7,
        img:"images/product-5.png",
        offer:"30% off",
        title:"Greco di Tufo I Capitani",
        cate:"red wine",
        oldprice:"45.00",
        price:"30.00",
        link:"/shop",
      },
      {
        id:8,
        img:"images/product-7.png",
        offer:"",
        title:" 2020 Limited Release Le Rosé ",
        cate:"white wine",
        oldprice:"39.00",
        price:"24.00",
        link:"/shop",
      },
]

export default Bestsellproducts;